### ISSUE TITLE
NodeJS Decrypt Error (bad decrypt)

### ISSUE THREAD

**Issue by DrauzJu** [keel/aes-cross#5]
I want to encrypt my data in Java and decrypt it in NodeJS, so to try it out I copied & pasted the sample code (using all default values). Nevertheless, I got the following error in NodeJS:
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

Can you help me?
Thank you very much in advance!

**Comment by keel** [comment]
looks like the key or iv error, can you past the code here?

**Comment by DrauzJu** [comment]
Encrypt data in Java

        byte[] key = { 1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6 };
        // iv size must be 16
        byte[] ivk = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

        try {
            AesInstance ai = AesInstance.getInstance(key, ivk);
            String enc = ai.encText(json);
            return enc;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }

Decrypt in Node
`        var aes = require('aes-cross');
        var key = new Buffer([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6]);
        var dec = aes.decText(data,key);`

**Comment by keel** [comment]
I have tested your code, but no error be found. What's your "json" and "enc" value?

**Comment by DrauzJu** [comment]
json:
{"auth":"$2a$10$0Q1W5QBySjQLPSO.HhVn.OJ2q2qf0ccGuAGD3CdyOY29ck/cAc.v.","timestamp":"2017-05-03-12-31","command":"GetKategorien"}

enc:
stYhXpgzHKvJlLdsxr3hKaOZ4JIiPGArZN3bJ9zdepmrN/8rERrl3ICi8VdvsxcvsulIJ7996Wc/2QeDvUkzhVLZSr2owzjmmKQlKBejEtnVOuQXUbKOCOLN3qrCloSrLK2RNwfV6LS9N+72xcU+Bnu3wocfUJSzAgSzYnkWFxi8dEWBxgkVRbx00ziRn+AC

**Comment by keel** [comment]
I test that and it's OK:

```
var aes = require('aes-cross');
var enc = 'stYhXpgzHKvJlLdsxr3hKaOZ4JIiPGArZN3bJ9zdepmrN/8rERrl3ICi8VdvsxcvsulIJ7996Wc/2QeDvUkzhVLZSr2owzjmmKQlKBejEtnVOuQXUbKOCOLN3qrCloSrLK2RNwfV6LS9N+72xcU+Bnu3wocfUJSzAgSzYnkWFxi8dEWBxgkVRbx00ziRn+AC';
var key = new Buffer([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6]);
var dec = aes.decText(enc, key);
console.log('dec:%j',dec);

//dec:"{\"auth\":\"$2a$10$0Q1W5QBySjQLPSO.HhVn.OJ2q2qf0ccGuAGD3CdyOY29ck/cAc.v.\",\"timestamp\":\"2017-05-03-12-31\",\"command\":\"GetKategorien\"}"
```

**Comment by DrauzJu** [comment]
Thank you very much for your help, I will try it again. Do you know if there are any local Node settings which can cause this issue?

**Comment by keel** [comment]
I can not reproduce your error. I use node 6.9.1, there's nothing to set on node, the default encoding is utf-8. 
I think you may review your node code carefully, the java's result is right.
