### ISSUE TITLE
Hi,may I have the horner to read the C/C++ part.I have been into it for days and still get inconsitent with the Java Web.Thanks

### ISSUE THREAD

**Issue by ghost** [keel/aes-cross#6]
Hi,may I have the horner to read the C/C++ part.I have been into it for days and still get inconsitent with the Java Web.Thanks

**Comment by keel** [comment]
Sorry , I have not write the independent C code, but you can use the openssl aes_core.c,aes_locl.h here:
https://github.com/openssl/openssl/tree/master/crypto/aes

and make sure the AES/CBC/PKCS5Padding is same as java, especially the padding, you can do the encrypt like this:
```C
int lenBuff = 0;
//str is what you want to encrypt.
int str_len = strlen(str);
AES_KEY aes;
if (str_len % AES_BLOCK_SIZE == 0) {
	lenBuff = str_len + AES_BLOCK_SIZE;
} else {
	lenBuff = (str_len / AES_BLOCK_SIZE + 1) * AES_BLOCK_SIZE;
}
inputString = (unsigned char*) calloc(lenBuff, sizeof(unsigned char));
encryptString = (unsigned char*) calloc(lenBuff, sizeof(unsigned char));
memset(inputString, 0, str_len + 1);
memset(encryptString, 0, lenBuff);
strncpy((char*) inputString, str, lenBuff);

//make the padding first
char array[16] = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09,
		0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10 };
if (str_len % 16 == 0) {
	for (int i = str_len; i < lenBuff; ++i) {
		inputString[i] = array[15];
	}
} else {
	int lenPad = 16 - str_len % 16;
	for (int i = str_len; i < str_len + lenPad; i++) {
		inputString[i] = array[lenPad - 1];
	}
}
//and then set the right key size and iv
AES_set_encrypt_key(akey, 128, &aes);
//cbc , iv
AES_cbc_encrypt((unsigned char*) inputString, encryptString, lenBuff, &aes,iv, AES_ENCRYPT);
//maybe you need base64...
base64AesString = new unsigned char[lenBuff * 2 + 4];
Base64Encode(encryptString, base64AesString, lenBuff);
```
And decryption:
```C
static char * aesDecrypt(JNIEnv *env, const char * base64AesString,
		unsigned char *akey, unsigned char *iv) {
	int lenBuff = 0;
	int base64EncrypeLen;
	unsigned char *base64DecryptString;
	unsigned char *decryptString;
	AES_KEY aes;
	int str_len = strlen(base64AesString);
	base64EncrypeLen = str_len;

	lenBuff = str_len;
	int i;
	AES_set_decrypt_key(akey, 128, &aes);
	decryptString = (unsigned char*) calloc(lenBuff, sizeof(unsigned char));
	base64DecryptString = (unsigned char*) calloc(base64EncrypeLen + 1,
			sizeof(unsigned char));

	memset(decryptString, 0, lenBuff);
	memset(base64DecryptString, 0, base64EncrypeLen + 1);

	int baseDeLen = Base64Decode(base64DecryptString,
			(unsigned char *) base64AesString, base64EncrypeLen, true);
	if (baseDeLen > 2) {
		baseDeLen = baseDeLen - 2;
	}
	//aes decrypt
	AES_cbc_encrypt(base64DecryptString, decryptString, baseDeLen, &aes, iv,
			AES_DECRYPT);
	int len = strlen((const char *) decryptString);
// padding back !
	int e = decryptString[len - 1];
	for (i = len - e; i < len; i++) {
		decryptString[i] = 0;
	}
	return (char *) decryptString;
}
```

**Comment by ghost** [comment]
really helpful.3Q

**Comment by ghost** [comment]
Like my last test demo with openssl/aes/cbc,it goes just fine when the cleartext is simple,combining with alphabets and numbers.But when it come to special characters like '\"',the encrypted result will fall badly different with the java web,which has been disturbing me for days.We use jsoned string to pass data between java and c/c++,so it is inevitable to have special charachters in the data.Could you spare me some time for the problem?I can pay you for your  time and work.3Q

**Comment by keel** [comment]
Please make sure both java and c use the same encoding, such as `utf-8`.
And check the url-encoding  when use http get/post to get the data.
If you still got problems, just paste your cleartext and encrypt result here, with the key,key size,iv,padding... so we try to figure it out together.

**Comment by huafeihuao0** [comment]
We have the problem solved in a compromised way.Before AES encrypting,I base64 the clearText to restrict the alphabets in "a-zA-Z/+=",which is supported by AES/CBC.In this way,we solve the cross-platform AES problem at the acceptable cost of the limited larger size of primary clearText.Your advice is significant and very helpful.Really thanks anyway.I have got your code reconstructed,and test it well.If you need,I can email to you for free.

**Comment by ghost** [comment]
I have my word,can you email me an cross-country  credit card ID or  a third-party pay platform like Alipay in China.My email address：yx16395175@163.com

**Comment by keel** [comment]
都在中国,可以加个微信
