### ISSUE TITLE
AES in GCM/CTR mode

### ISSUE THREAD

**Issue by AbhilashDawar** [keel/aes-cross#7]
Is AES in GCM/CTR mode supported in this module? Preferably GCM. If possible, help me setting it up.
I have tried a lot of modules, this was the best fit I could find. I had to encrypt in JS and decrypt in Java.

**Comment by keel** [comment]
AES-GCM, I think there are modules in nodejs and java. 
nodejs: https://www.npmjs.com/package/node-aes-gcm

Just make sure keysize to be same and use zero-padding mode.

**Comment by keel** [comment]
I'm not familiar with AES-GCM, but it maybe important. I found this article may help:
https://medium.com/@encryb/comparing-performance-of-javascript-cryptography-libraries-42fb138116f3

Maybe you can find pure javascript AES-GCM there.And I found GCM no need padding, make sure key, key size, and iv to be the same in both java and js.

**Comment by AbhilashDawar** [comment]
Thank you, @keel for your help. Though work is still going on.
